name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for PyPI trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/self-ai-operating-computer

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install build tools
      run: python -m pip install build setuptools wheel
      
    - name: Build package
      run: python -m build
      
    - name: Check if version exists on PyPI
      id: check-version
      run: |
        VERSION=$(python setup.py --version)
        if curl -s "https://pypi.org/pypi/self-ai-operating-computer/$VERSION/json" | grep -q "Not Found"; then
          echo "version_exists=false" >> $GITHUB_OUTPUT
        else
          echo "version_exists=true" >> $GITHUB_OUTPUT
          echo "Version $VERSION already exists on PyPI. Skipping upload."
          exit 1
        fi
    
    - name: Publish to PyPI
      if: steps.check-version.outputs.version_exists == 'false'
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
